# Generated by Django 3.0.6 on 2020-06-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_auto_20200615_0122'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('label', 'user'), name='unique_tags'),
        ),
    ]
